package cl.dbnet.consulta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-09-25T17:08:14.890-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.dbnet.cl", name = "Service1HttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Service1HttpPost {

    @WebMethod(operationName = "ConsultaEstado")
    @WebResult(name = "string", targetNamespace = "http://www.dbnet.cl", partName = "Body")
    public java.lang.String consultaEstado(
        @WebParam(partName = "ruc", name = "ruc", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruc,
        @WebParam(partName = "tipo_docu", name = "tipo_docu", targetNamespace = "http://www.dbnet.cl")
        java.lang.String tipoDocu,
        @WebParam(partName = "foli_inte", name = "foli_inte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String foliInte,
        @WebParam(partName = "serie_inte", name = "serie_inte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String serieInte
    );

    @WebMethod(operationName = "ActualizaEstadoDoc")
    @WebResult(name = "int", targetNamespace = "http://www.dbnet.cl", partName = "Body")
    public int actualizaEstadoDoc(
        @WebParam(partName = "ruc", name = "ruc", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruc,
        @WebParam(partName = "CodiEmpr", name = "CodiEmpr", targetNamespace = "http://www.dbnet.cl")
        java.lang.String codiEmpr,
        @WebParam(partName = "tipo_docu", name = "tipo_docu", targetNamespace = "http://www.dbnet.cl")
        java.lang.String tipoDocu,
        @WebParam(partName = "foli_inte", name = "foli_inte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String foliInte,
        @WebParam(partName = "serie_inte", name = "serie_inte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String serieInte,
        @WebParam(partName = "Estado", name = "Estado", targetNamespace = "http://www.dbnet.cl")
        java.lang.String estado
    );
}
