package cl.dbnet.consulta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-09-25T17:08:14.882-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.dbnet.cl", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebMethod(operationName = "ConsultaEstado", action = "http://www.dbnet.cl/ConsultaEstado")
    @RequestWrapper(localName = "ConsultaEstado", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.ConsultaEstado")
    @ResponseWrapper(localName = "ConsultaEstadoResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.ConsultaEstadoResponse")
    @WebResult(name = "ConsultaEstadoResult", targetNamespace = "http://www.dbnet.cl")
    public java.lang.String consultaEstado(
        @WebParam(name = "ruc", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruc,
        @WebParam(name = "tipo_docu", targetNamespace = "http://www.dbnet.cl")
        int tipoDocu,
        @WebParam(name = "foli_inte", targetNamespace = "http://www.dbnet.cl")
        int foliInte,
        @WebParam(name = "serie_inte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String serieInte
    );

    @WebMethod(operationName = "ActualizaEstadoDoc", action = "http://www.dbnet.cl/ActualizaEstadoDoc")
    @RequestWrapper(localName = "ActualizaEstadoDoc", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.ActualizaEstadoDoc")
    @ResponseWrapper(localName = "ActualizaEstadoDocResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.ActualizaEstadoDocResponse")
    @WebResult(name = "ActualizaEstadoDocResult", targetNamespace = "http://www.dbnet.cl")
    public int actualizaEstadoDoc(
        @WebParam(name = "ruc", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruc,
        @WebParam(name = "CodiEmpr", targetNamespace = "http://www.dbnet.cl")
        int codiEmpr,
        @WebParam(name = "tipo_docu", targetNamespace = "http://www.dbnet.cl")
        int tipoDocu,
        @WebParam(name = "foli_inte", targetNamespace = "http://www.dbnet.cl")
        int foliInte,
        @WebParam(name = "serie_inte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String serieInte,
        @WebParam(name = "Estado", targetNamespace = "http://www.dbnet.cl")
        java.lang.String estado
    );
}
