package cl.dbnet.carga;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-09-25T17:10:50.539-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "CustomerETDLoadASP",
        wsdlLocation = "https://farenet.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL",
        //wsdlLocation = "https://pruebas.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL",
                  targetNamespace = "http://www.dbnet.cl") 
public class CustomerETDLoadASP extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.dbnet.cl", "CustomerETDLoadASP");
    public final static QName CustomerETDLoadASPSoap12 = new QName("http://www.dbnet.cl", "CustomerETDLoadASPSoap12");
    public final static QName CustomerETDLoadASPSoap = new QName("http://www.dbnet.cl", "CustomerETDLoadASPSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://farenet.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL");
            //url = new URL("https://pruebas.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerETDLoadASP.class.getName())
                .log(java.util.logging.Level.INFO,
                        "Can not initialize the default wsdl from {0}", "https://factura.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL");
                        //"Can not initialize the default wsdl from {0}", "https://pruebas.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public CustomerETDLoadASP(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerETDLoadASP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerETDLoadASP() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CustomerETDLoadASP(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerETDLoadASP(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerETDLoadASP(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CustomerETDLoadASPSoap
     */
    @WebEndpoint(name = "CustomerETDLoadASPSoap12")
    public CustomerETDLoadASPSoap getCustomerETDLoadASPSoap12() {
        return super.getPort(CustomerETDLoadASPSoap12, CustomerETDLoadASPSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerETDLoadASPSoap
     */
    @WebEndpoint(name = "CustomerETDLoadASPSoap12")
    public CustomerETDLoadASPSoap getCustomerETDLoadASPSoap12(WebServiceFeature... features) {
        return super.getPort(CustomerETDLoadASPSoap12, CustomerETDLoadASPSoap.class, features);
    }


    /**
     *
     * @return
     *     returns CustomerETDLoadASPSoap
     */
    @WebEndpoint(name = "CustomerETDLoadASPSoap")
    public CustomerETDLoadASPSoap getCustomerETDLoadASPSoap() {
        return super.getPort(CustomerETDLoadASPSoap, CustomerETDLoadASPSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerETDLoadASPSoap
     */
    @WebEndpoint(name = "CustomerETDLoadASPSoap")
    public CustomerETDLoadASPSoap getCustomerETDLoadASPSoap(WebServiceFeature... features) {
        return super.getPort(CustomerETDLoadASPSoap, CustomerETDLoadASPSoap.class, features);
    }

}
