package cl.dbnet.carga;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-09-25T17:10:50.534-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.dbnet.cl", name = "CustomerETDLoadASPSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerETDLoadASPSoap {

    @WebMethod(action = "http://www.dbnet.cl/putCustomerETDLoadXML")
    @RequestWrapper(localName = "putCustomerETDLoadXML", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.PutCustomerETDLoadXML")
    @ResponseWrapper(localName = "putCustomerETDLoadXMLResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.PutCustomerETDLoadXMLResponse")
    @WebResult(name = "putCustomerETDLoadXMLResult", targetNamespace = "http://www.dbnet.cl")
    public java.lang.String putCustomerETDLoadXML(
        @WebParam(name = "lsXML", targetNamespace = "http://www.dbnet.cl")
        java.lang.String lsXML
    );

    @WebMethod(action = "http://www.dbnet.cl/putCustomerETDLoad")
    @RequestWrapper(localName = "putCustomerETDLoad", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.PutCustomerETDLoad")
    @ResponseWrapper(localName = "putCustomerETDLoadResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.PutCustomerETDLoadResponse")
    @WebResult(name = "putCustomerETDLoadResult", targetNamespace = "http://www.dbnet.cl")
    public Mensaje putCustomerETDLoad(
        @WebParam(name = "Extras", targetNamespace = "http://www.dbnet.cl")
        Extras extras,
        @WebParam(name = "Encabezado", targetNamespace = "http://www.dbnet.cl")
       Encabezado encabezado,
        @WebParam(name = "Detalles", targetNamespace = "http://www.dbnet.cl")
        ArrayOfDetalle detalles,
        @WebParam(name = "DescuentosRecargosyOtros", targetNamespace = "http://www.dbnet.cl")
        DescuentosRecargosyOtros descuentosRecargosyOtros
    );
}
