package cl.dbnet.pdf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-09-25T17:19:16.568-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "consultaDocumentosPeru", 
                  wsdlLocation = "https://farenet.ecomprobantes.pe/wssConsultaDocPeru/consultaDocumentosPeru.asmx?WSDL",
        //wsdlLocation = "https://pruebas.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL",
                  targetNamespace = "http://www.dbnet.cl") 
public class ConsultaDocumentosPeru extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.dbnet.cl", "consultaDocumentosPeru");
    public final static QName ConsultaDocumentosPeruSoap = new QName("http://www.dbnet.cl", "consultaDocumentosPeruSoap");
    public final static QName ConsultaDocumentosPeruSoap12 = new QName("http://www.dbnet.cl", "consultaDocumentosPeruSoap12");
    static {
        URL url = null;
        try {
            url = new URL("https://farenet.ecomprobantes.pe/wssConsultaDocPeru/consultaDocumentosPeru.asmx?WSDL");
            //url = new URL("https://pruebas.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaDocumentosPeru.class.getName())
                .log(java.util.logging.Level.INFO,
                        "Can not initialize the default wsdl from {0}", "https://factura.ecomprobantes.pe/wssConsultaDocPeru/consultaDocumentosPeru.asmx?WSDL");
            //"Can not initialize the default wsdl from {0}", "https://pruebas.ecomprobantes.pe/wssCustomerETDLoadBDUBL21/CustomerETDLoadASP.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaDocumentosPeru(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaDocumentosPeru(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaDocumentosPeru() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ConsultaDocumentosPeru(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaDocumentosPeru(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaDocumentosPeru(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ConsultaDocumentosPeruSoap
     */
    @WebEndpoint(name = "consultaDocumentosPeruSoap")
    public ConsultaDocumentosPeruSoap getConsultaDocumentosPeruSoap() {
        return super.getPort(ConsultaDocumentosPeruSoap, ConsultaDocumentosPeruSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaDocumentosPeruSoap
     */
    @WebEndpoint(name = "consultaDocumentosPeruSoap")
    public ConsultaDocumentosPeruSoap getConsultaDocumentosPeruSoap(WebServiceFeature... features) {
        return super.getPort(ConsultaDocumentosPeruSoap, ConsultaDocumentosPeruSoap.class, features);
    }


    /**
     *
     * @return
     *     returns ConsultaDocumentosPeruSoap
     */
    @WebEndpoint(name = "consultaDocumentosPeruSoap12")
    public ConsultaDocumentosPeruSoap getConsultaDocumentosPeruSoap12() {
        return super.getPort(ConsultaDocumentosPeruSoap12, ConsultaDocumentosPeruSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaDocumentosPeruSoap
     */
    @WebEndpoint(name = "consultaDocumentosPeruSoap12")
    public ConsultaDocumentosPeruSoap getConsultaDocumentosPeruSoap12(WebServiceFeature... features) {
        return super.getPort(ConsultaDocumentosPeruSoap12, ConsultaDocumentosPeruSoap.class, features);
    }

}
