package cl.dbnet.pdf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-09-25T17:19:16.558-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.dbnet.cl", name = "consultaDocumentosPeruSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultaDocumentosPeruSoap {

    /**
     * Permite la obtención del CDR de un Documento Electrónico
     */
    @WebMethod(action = "http://www.dbnet.cl/getDocumentoCDR")
    @RequestWrapper(localName = "getDocumentoCDR", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.GetDocumentoCDR")
    @ResponseWrapper(localName = "getDocumentoCDRResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.GetDocumentoCDRResponse")
    @WebResult(name = "getDocumentoCDRResult", targetNamespace = "http://www.dbnet.cl")
    public ArrayOfString getDocumentoCDR(
        @WebParam(name = "_ruttEmpr", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruttEmpr,
        @WebParam(name = "_folioDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String folioDTE,
        @WebParam(name = "_tipoDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String tipoDTE,
        @WebParam(name = "_serieInte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String serieInte,
        @WebParam(name = "_fechaDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String fechaDTE,
        @WebParam(name = "_monTotal", targetNamespace = "http://www.dbnet.cl")
        java.lang.String monTotal
    );

    /**
     * Permite la obtención del último número de versión
     */
    @WebMethod(operationName = "ObtnerVersion", action = "http://www.dbnet.cl/ObtnerVersion")
    @RequestWrapper(localName = "ObtnerVersion", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.ObtnerVersion")
    @ResponseWrapper(localName = "ObtnerVersionResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.ObtnerVersionResponse")
    @WebResult(name = "ObtnerVersionResult", targetNamespace = "http://www.dbnet.cl")
    public java.lang.String obtnerVersion();

    /**
     * Permite la obtención del XML de un Documento Electrónico
     */
    @WebMethod(action = "http://www.dbnet.cl/getDocumentoXML")
    @RequestWrapper(localName = "getDocumentoXML", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.GetDocumentoXML")
    @ResponseWrapper(localName = "getDocumentoXMLResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.GetDocumentoXMLResponse")
    @WebResult(name = "getDocumentoXMLResult", targetNamespace = "http://www.dbnet.cl")
    public ArrayOfString getDocumentoXML(
        @WebParam(name = "_ruttEmpr", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruttEmpr,
        @WebParam(name = "_folioDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String folioDTE,
        @WebParam(name = "_tipoDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String tipoDTE,
        @WebParam(name = "_serieInte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String serieInte,
        @WebParam(name = "_fechaDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String fechaDTE,
        @WebParam(name = "_monTotal", targetNamespace = "http://www.dbnet.cl")
        java.lang.String monTotal
    );

    /**
     * Permite registrar una petición de descarga de información.
     */
    @WebMethod(action = "http://www.dbnet.cl/setRegistraPeticionDescarga")
    @RequestWrapper(localName = "setRegistraPeticionDescarga", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.SetRegistraPeticionDescarga")
    @ResponseWrapper(localName = "setRegistraPeticionDescargaResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.SetRegistraPeticionDescargaResponse")
    @WebResult(name = "setRegistraPeticionDescargaResult", targetNamespace = "http://www.dbnet.cl")
    public boolean setRegistraPeticionDescarga(
        @WebParam(name = "lstDocs", targetNamespace = "http://www.dbnet.cl")
       ArrayOfString lstDocs,
        @WebParam(name = "codiEmpr", targetNamespace = "http://www.dbnet.cl")
        java.lang.String codiEmpr,
        @WebParam(name = "ruc", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruc,
        @WebParam(name = "user", targetNamespace = "http://www.dbnet.cl")
        java.lang.String user,
        @WebParam(name = "guid", targetNamespace = "http://www.dbnet.cl")
        java.lang.String guid,
        @WebParam(name = "ruta", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruta,
        @WebParam(name = "correo", targetNamespace = "http://www.dbnet.cl")
        java.lang.String correo,
        @WebParam(name = "rutaWeb", targetNamespace = "http://www.dbnet.cl")
        java.lang.String rutaWeb
    );

    /**
     * Permite la obtención del PDF de un Documento Electrónico
     */
    @WebMethod(action = "http://www.dbnet.cl/getDocumentoPDF")
    @RequestWrapper(localName = "getDocumentoPDF", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.GetDocumentoPDF")
    @ResponseWrapper(localName = "getDocumentoPDFResponse", targetNamespace = "http://www.dbnet.cl", className = "cl.dbnet.GetDocumentoPDFResponse")
    @WebResult(name = "getDocumentoPDFResult", targetNamespace = "http://www.dbnet.cl")
    public ArrayOfString getDocumentoPDF(
        @WebParam(name = "_ruttEmpr", targetNamespace = "http://www.dbnet.cl")
        java.lang.String ruttEmpr,
        @WebParam(name = "_folioDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String folioDTE,
        @WebParam(name = "_tipoDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String tipoDTE,
        @WebParam(name = "_serieInte", targetNamespace = "http://www.dbnet.cl")
        java.lang.String serieInte,
        @WebParam(name = "_fechaDTE", targetNamespace = "http://www.dbnet.cl")
        java.lang.String fechaDTE,
        @WebParam(name = "_monTotal", targetNamespace = "http://www.dbnet.cl")
        java.lang.String monTotal
    );
}
