package cl.dbnet.bajas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-09-25T17:05:54.744-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "WssCargaBajas", 
                  wsdlLocation = "https://farenet.ecomprobantes.pe/wssCargaBajas/cargaBajas.asmx?WSDL",
                  targetNamespace = "http://www.dbnet.cl") 
public class WssCargaBajas extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.dbnet.cl", "WssCargaBajas");
    public final static QName WssCargaBajasSoap = new QName("http://www.dbnet.cl", "WssCargaBajasSoap");
    public final static QName WssCargaBajasSoap12 = new QName("http://www.dbnet.cl", "WssCargaBajasSoap12");
    static {
        URL url = null;
        try {
            url = new URL("https://farenet.ecomprobantes.pe/wssCargaBajas/cargaBajas.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WssCargaBajas.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://factura.ecomprobantes.pe/wssCargaBajas/cargaBajas.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WssCargaBajas(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WssCargaBajas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WssCargaBajas() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WssCargaBajas(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WssCargaBajas(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WssCargaBajas(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WssCargaBajasSoap
     */
    @WebEndpoint(name = "WssCargaBajasSoap")
    public WssCargaBajasSoap getWssCargaBajasSoap() {
        return super.getPort(WssCargaBajasSoap, WssCargaBajasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WssCargaBajasSoap
     */
    @WebEndpoint(name = "WssCargaBajasSoap")
    public WssCargaBajasSoap getWssCargaBajasSoap(WebServiceFeature... features) {
        return super.getPort(WssCargaBajasSoap, WssCargaBajasSoap.class, features);
    }


    /**
     *
     * @return
     *     returns WssCargaBajasSoap
     */
    @WebEndpoint(name = "WssCargaBajasSoap12")
    public WssCargaBajasSoap getWssCargaBajasSoap12() {
        return super.getPort(WssCargaBajasSoap12, WssCargaBajasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WssCargaBajasSoap
     */
    @WebEndpoint(name = "WssCargaBajasSoap12")
    public WssCargaBajasSoap getWssCargaBajasSoap12(WebServiceFeature... features) {
        return super.getPort(WssCargaBajasSoap12, WssCargaBajasSoap.class, features);
    }

}
